### ISSUE TITLE
Version already defined, compile error

### ISSUE THREAD

**Issue by larroy** [xitrum-framework/xitrum#496]
Hi

While compiling xitrum I get the following error, any ideas?

[info] Compiling 118 Scala sources to /home/piotr/devel/xitrum/target/scala-2.11/classes...
[error] /home/piotr/devel/xitrum/src/main/scala/xitrum/Version.scala:3: Version is already defined as class Version
[error] class Version {
[error]       ^
[error] one error found

**Comment by ngocdaothanh** [comment]
Please manually delete (may be several times) `src/main/scala/xitrum/Version.scala` and compile again.

This is an inconvenience caused by `sourceGenerators` in build.sbt:
https://github.com/xitrum-framework/xitrum/blob/master/build.sbt#L26

If you have a solution, please share. It seems that SBT tries to generate and compile the file multiple times.

**Comment by ngocdaothanh** [comment]
I've fixed the problem with this commit:
https://github.com/xitrum-framework/xitrum/commit/cf1642a4ae983db2ae94c6da0170f16a92dcf988

Please try.
