### ISSUE TITLE
100 cpu usage on akka.actor.LightArrayRevolverScheduler.waitNanos

### ISSUE THREAD

**Issue by larroy** [xitrum-framework/xitrum#502]
Hi

I have a trivial app based on xitrum extending Action with the same configuration as in the example app and I get 100% cpu on the method of the subject as seen in visualVM

I'm not using akka outside of xitrum at all.

I tried to reproduce the problem with a minimal repository doing the same as in my project and wasn't able.   I used the same dependencies on sbt, compiler version etc.

The only difference is in the logfile of the bigger project I get an exception:

15:33:31.648 [nioEventLoopGroup-4-1] DEBUG io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely because Thread.currentThread().interrupt() was called. Use NioEventLoop.shutdownGracefully() to shutdown the NioEventLoop.

While in the small test project where I tried to reproduce I didn't.

Any ideas on where could I look further to fix this issue?

This is the full output.

[info] Loading project definition from /home/piotr/devel/vadis/project
[info] Set current project to vadis (in build file:/home/piotr/devel/vadis/)
[info] Compiling 1 Scala source to /home/piotr/devel/vadis/target/scala-2.10/classes...
[info] Running com.here.vadis.Main serve
15:33:29.815 [run-main-0] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
15:33:30.184 [run-main-0] INFO  xitrum.package$ - Load tmp/routes.cache or recollect routes...
15:33:31.110 [run-main-0] INFO  xitrum.package$ - No template engine is configured
[INFO] [01/21/2015 15:33:31.117] [run-main-0] [Registry$(akka://xitrum)] Glokka actor registry "xitrum.sockjs.SockJsAction$" starts in local mode
[INFO] [01/21/2015 15:33:31.140] [run-main-0] [Registry$(akka://xitrum)] Glokka actor registry "metrics" starts in local mode
15:33:31.420 [run-main-0] INFO  xitrum.package$ - Normal routes:
GET  /tile/:quad  com.here.vadis.server.action.Tiles
15:33:31.425 [run-main-0] INFO  xitrum.package$ - Xitrum routes:
GET  /xitrum/xitrum.js       xitrum.js
GET  /xitrum/metrics/viewer  xitrum.metrics.XitrumMetricsViewer
15:33:31.428 [run-main-0] INFO  xitrum.package$ - Xitrum SockJS routes:
/xitrum/metrics/channel  xitrum.metrics.XitrumMetricsChannel  websocket: true, cookie_needed: false
15:33:31.434 [run-main-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetectionLevel: simple
15:33:31.441 [run-main-0] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
15:33:31.449 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
15:33:31.450 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
15:33:31.450 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
15:33:31.450 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
15:33:31.452 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - Java version: 7
15:33:31.452 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
15:33:31.452 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
15:33:31.452 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
15:33:31.538 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - Javassist: available
15:33:31.538 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
15:33:31.538 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
15:33:31.538 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
15:33:31.560 [run-main-0] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
15:33:31.560 [run-main-0] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
15:33:31.587 [run-main-0] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0xefdea4727f98b921 (took 1 ms)
15:33:31.612 [run-main-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
15:33:31.612 [run-main-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
15:33:31.615 [run-main-0] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%1)
15:33:31.615 [run-main-0] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
15:33:31.628 [nioEventLoopGroup-2-1] DEBUG i.n.util.internal.PlatformDependent - UID: 1000
15:33:31.633 [run-main-0] INFO  xitrum.package$ - HTTP server started on port 8000
15:33:31.641 [run-main-0] INFO  xitrum.package$ - HTTPS server started on port 4430
15:33:31.642 [run-main-0] INFO  xitrum.package$ - Xitrum 3.22 started in development mode
15:33:31.643 [run-main-0] WARN  xitrum.package$ - *** For security, change secureKey in config/xitrum.conf to your own! ***
15:33:31.643 [run-main-0] INFO  com.here.vadis.Main$ - Success.
15:33:31.643 [run-main-0] INFO  com.here.vadis.Main$ - =========== finished successfully ================
15:33:31.648 [nioEventLoopGroup-4-1] DEBUG io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely because Thread.currentThread().interrupt() was called. Use NioEventLoop.shutdownGracefully() to shutdown the NioEventLoop.
15:33:31.651 [nioEventLoopGroup-2-1] DEBUG io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely because Thread.currentThread().interrupt() was called. Use NioEventLoop.shutdownGracefully() to shutdown the NioEventLoop.

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"

**Comment by larroy** [comment]
The problem started while I was investigating that scalikejdbc connections were not being returned to the pool after use.   This happens only when I get the interrupt exception in netty, otherwise everything works.

Seems there's a race condition somewhere, I was able to reproduce this problem in a small repository, happens when there's some logic after Server.start()

I have reproduced the problem here:

https://github.com/larroy/xitrum_issue_502

I would appreciate some guidance on how to fix it.

**Comment by larroy** [comment]
http://netty.io/4.0/xref/io/netty/channel/nio/NioEventLoop.html#632

**Comment by ngocdaothanh** [comment]
In the example project at https://github.com/larroy/xitrum_issue_502, you call `sys.exit` to stop the program. The Netty I/O threads are interrupted and they log out `"Thread.currentThread().interrupt() was called.`. This behavior is normal.

In your real project, you say that you are extending `xitrum.Action`. As explained in the [Xitrum Guide](http://xitrum-framework.github.io/guide/3.22/en/action_view.html), there are 3 kinds of actions: `Action`, `FutureAction`, and `ActorAction` (there's also `SockJsAction`, but it's just a special kind of `ActorAction`).

`Action` runs directly on a Netty I/O thread. So I think the symptom you are seeing is because:
* The current thread is interrupted by scalikejdbc (maybe, to avoid leaking connections?).
* This thread is a Netty I/O thread, so Netty will log out the message as you have seen.
* The log is at DEBUG level. By default Xitrum skeleton projects (xitrum-new](https://github.com/ngocdaothanh/xitrum-new) and [xitrum-demos](https://github.com/ngocdaothanh/xitrum-demos)) only log Netty's log when log level is [INFO or above](https://github.com/xitrum-framework/xitrum-new/blob/master/config/logback.xml#L6). In the example project you don't have a Logback config file, so everything is logged.

So I think maybe you should improve like this:
* Return scalikejdbc connections back to the pool after use.
* Instead of `extends Action`, try using `extends FutureAction`, to avoid blocking Netty I/O threads. In this case Akka's thread pool is used instead of Netty's thread pool. Maybe you have tried this and you have seen 100% CPU usage at `akka.actor.LightArrayRevolverScheduler.waitNanos` because maybe Akka doesn't spawn new threads when existing ones stop, so gradually Akka is out of threads.

FYI, interrupting threads is the de facto way to [tell threads to stop](http://stackoverflow.com/questions/19894607/java-how-to-stop-thread).

**Comment by ngocdaothanh** [comment]
Yes I can see 100% CPU at app's exit when running with SBT. It's because you call `sys.exit` in your app, and SBT intercepts `sys.exitP, and your app can't exit cleanly:
http://stackoverflow.com/questions/21464673/sbt-trapexitsecurityexception-thrown-at-sbt-run

Something is stuck and it causes 100% CPU and your app can't exit.

If you run without SBT, then you don't see the problem. Like this:

Add to project/plugins.sbt (see https://github.com/xitrum-framework/xitrum-package):
```
addSbtPlugin("tv.cntt" % "xitrum-package" % "1.9")
```

Add to build.sbt:
```
XitrumPackage.copy()
```

Package your app:
```
sbt xitrum-package
```

Directory target/xitrum will be created.
Run:
```
cd target/xitrum
java -cp "lib/*" com.larroy.Main hi
```
