### ISSUE TITLE
Scala IDE 4.1.0 error with xgettext

### ISSUE THREAD

**Issue by caiiiycuk** [xitrum-framework/xitrum#543]
If i checkout xitrum-new and import project in eclipse (sbt eclipse), then i eclipse shows error:
```
Compiler plugin xgettext_2.11-1.3.jar is cross-compiled with incompatible version for this project: 2.11.0 vs 2.11.6
```

**Comment by caiiiycuk** [comment]
The problem occurs only in Scala IDE 4.1.0

**Comment by ngocdaothanh** [comment]
Please fix Scala IDE setting like this:
* Right click xitrum-new project in the IDE.
* Go to Scala → Compiler → Build Manager, and uncheck the `withVersionClasspathValidator` option.

![](https://qiita-image-store.s3.amazonaws.com/0/41616/ee108a56-388d-1253-bb21-75a5aff535cb.png)

Because `withVersionClasspathValidator` is a [special feature of Scala IDE](http://scala-ide.org/docs/current-user-doc/faq/index.html#Scala_IDE_complains_about_%E2%80%98____is_cross-compiled_with_an_incompatible_version_of_Scala____%E2%80%99),
I think this is a bug of Scala IDE 4.1.0.
Please report the bug to them.

**Comment by caiiiycuk** [comment]
> I think this is a bug of Scala IDE 4.1.0.

Does the xgettext_2.11 is compatible with Scala 2.11.6?

**Comment by ngocdaothanh** [comment]
Yes. You can try with SBT.
(There's `scalaVersion` in build.sbt of xitrum-new is set to `2.11.6` by default.)
