### ISSUE TITLE
JavaScript error at metrics detail page of actions

### ISSUE THREAD

**Issue by ngocdaothanh** [xitrum-framework/xitrum#572]
Steps to reproduce:

Run xitrum-demos. In the metrics page, click an action:
<img width="596" alt="1" src="https://cloud.githubusercontent.com/assets/10095/9805489/d79bcf74-587c-11e5-9954-7e5bfc896313.png">

The detail page is has JS error:
<img width="582" alt="2" src="https://cloud.githubusercontent.com/assets/10095/9805490/d7a2a15a-587c-11e5-8633-d3e60c4dd357.png">

**Comment by georgeOsdDev** [comment]
@ngocdaothanh san

This bug seems that cause by "gauge" of metrics are removed by this commit.

https://github.com/xitrum-framework/xitrum/commit/60638544dabbd4de16e527a294e4abce9a10a32e#diff-f49bab599ff97ee81aeea59bf2881e95L61

And so #571 need to be reverted to collect execution time of each action.
May I revert these two commit?

**Comment by ngocdaothanh** [comment]
Oh sorry, I mistakenly removed "gauge" in that commit!
Please let me do the revert myself.

**Comment by georgeOsdDev** [comment]
:+1:
