### ISSUE TITLE
Support Scala 2.12

### ISSUE THREAD

**Issue by everylifetechnologies** [xitrum-framework/xitrum#645]
Do you have plans to update the build for 2.12.1? They also recommend using sbt 0.13.13.

http://scala-lang.org/news/2.12.0
http://scala-lang.org/news/2.12.1

**Comment by ngocdaothanh** [comment]
Yes, I've been waiting for dependency Scala libraries used by Xitrum to be updated to use Scala 2.12.

Currently, the only remaining one is [curly](https://github.com/m3dev/curly/issues/10). But because it's only used in tests, I plan to replace it with something else, and release a new Xitrum version very soon (this week).

**Comment by everylifetechnologies** [comment]
Thanks and great work on Xitrum!

**Comment by ngocdaothanh** [comment]
I've just released Xitrum 3.28.2. This version adds support for Scala 2.12.

To update Xitrum in your project, see this example:
https://github.com/xitrum-framework/xitrum-demos/commit/30710c97dc12d97565e5f3e26385cbd24ea63549

**Comment by everylifetechnologies** [comment]
Thanks!
