### ISSUE TITLE
Why is the actor system is hardcoded?

### ISSUE THREAD

**Issue by photex** [xitrum-framework/xitrum#655]
Howdy! 

Decided to try out xitrum to add a sockjs endpoint to an existing akka cluster application. I am confused by the decision to hard-code the actor system that xitrum uses. I'm interested in submitting a PR that allows an application to provide their own actor system for xitrum to use but wanted to make sure I wasn't treading on already discussed design.

**Comment by ngocdaothanh** [comment]
Several years ago, I came to Scala and Akka from Erlang. There was usually no need for multiple actor systems.

Xitrum uses the actor system [named "xitrum"](https://github.com/xitrum-framework/xitrum/blob/master/src/main/scala/xitrum/Config.scala#L297), but it uses the top level "akka" config, see akka.conf and xitrum.conf:
https://github.com/xitrum-framework/xitrum-new/tree/master/config

> allows an application to provide their own actor system for xitrum

I think you can modify the source code so that you can provide a config for the actor system that Xitrum creates, so that if you have multiple actor systems, you can configure them independently.

**Comment by photex** [comment]
My concern isn't being able to configure them. I know that is possible. I'm concerned about creating multiple actor systems, these are heavyweight and create N threads, and I'm unsure whether it's a good idea to have multiple actor systems in a node when using the akka cluster facility.

**Comment by ngocdaothanh** [comment]
N is around twice of the number of CPU cores, so it should not be a problem if you only have several actor systems.

**Comment by photex** [comment]
Sorry to not respond for such a while. I've done some testing and you're correct. My other actor system can be configured separately from xitrum easily and this there is minimal impact.

Only potential concern comes about when clustering. If I wanted to enable clustering for my actor system as well as xitrum, I'd end up with having to specify multiple cluster port bindings right?

**Comment by ngocdaothanh** [comment]
> multiple cluster port bindings right?

Yes, I think so, although I haven't tried that before.
